#!/bin/bash
# vim: et ts=2 sw=2

log_lvl_num() {
  num=0
  case "$1" in
    DEBUG) num=100;;
    INFO | 2** | info | Info | infO) num=200;;
    WARN) num=300;;
    ERROR) num=400;;
  esac
  printf '%s' $num
}

log_anyway() {
  lvl="$1"; shift
  col=0
  case "$lvl" in
    DEBUG) col=111;;
    WARN) col=112;;
    INFO) col=168;;
    ERROR) col=192;;
  esac

  printf '[ \x1b[38;5;'$col'm%10s\x1b[m ] :: %s\n' "$lvl" "$*"
}

log_() {
  num="$(log_lvl_num "$1")"

  if test "$num" -ge "${LOG_LEVEL:-200}"
  then
    log_anyway "$@"
  fi
}

log_debug() {
  log_ DEBUG "$@"
}

log_info() {
  log_ INFO "$@"
}

log_warn() {
  log_ WARN "$@"
}

log_error() {
  log_ ERROR "$@"
}

log_level() {
  num="$(log_lvl_num "$1")"
  log_anyway INFO Setting LOG_LEVEL "<- $1 ~ $num"
  export LOG_LEVEL="$num"
}
